### ISSUE TITLE
Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by StevePrescott** [ten24/slatwall#3150]
Operating System: Windows 7
CFML Server:	ColdFusion Server: 11,0,04,293328
DB Dialect: 		MySQL
Slatwall Version:	4.0.000

After updating to v4.0 the Primary Navigation no longer functions. The Javascript console shows the following error:

Uncaught Error: [$injector:modulerr]

http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=slatwalladmin&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.14%2F%24injector%2Fmodulerr%3Fp0%3DngSlatwall%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.3.14%252F%2524injector%252Fnomod%253Fp0%253DngSlatwall%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A6%253A417%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A21%253A412%250A%2520%2520%2520%2520at%2520a%2520(http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A21%253A53)%250A%2520%2520%2520%2520at%2520w.bootstrap%2520(http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A21%253A296)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A35%253A116%250A%2520%2520%2520%2520at%2520s%2520(http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A7%253A302)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A34%253A399)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A35%253A63%250A%2520%2520%2520%2520at%2520s%2520(http%253A%252F%252Fwww.mgtcontrols.loc%252FSlatwall%252Fclient%252Flib%252Fangular%252Fangular.min.js%253A7%253A302)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A6%3A417%0A%20%20%20%20at%20http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A35%3A320%0A%20%20%20%20at%20s%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A7%3A302)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A34%3A399)%0A%20%20%20%20at%20http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A35%3A63%0A%20%20%20%20at%20s%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A7%3A302)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A34%3A399)%0A%20%20%20%20at%20ab%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A38%3A135)%0A%20%20%20%20at%20d%20(http%3A%2F%2Fwww.mgtcontrols.loc%2FSlatwall%2Fclient%2Flib%2Fangular%2Fangular.min.js%3A17%3A381

**Comment by rmarchandTen24** [comment]
this may be an issue related to the gzipping of js.

try adding <cfset variables.framework.hibachi.gzipJavascript = false /> to
your custom/config/configFramework.cfc

**Comment by StevePrescott** [comment]
Thank you, that worked to address the problem. Any idea if this is somehow unique to my scenario and should be a post installation task I should be doing for all v4 sites?

**Comment by rmarchandTen24** [comment]
We have tested it in a bunch of scenarios but are still trying to narrow it
down. We have found it in Windows 7, MySQL, IIS set ups only so far. I'd
like to assume it to be related to IIS as it can handle gzip on it's own
without the aid of the ngcompressor.cfc.

**Comment by bowler865** [comment]
I tried the suggested fix and am still getting the angular.js errors and menus not loading in the admin. I added the code first to the /custom/config/configFramework.cfc and reloaded with no change. I then added it to the /config/configFramework.cfc just to see if it would make a difference, reloaded and still receiving the same errors. Any other ideas?

**Comment by bowler865** [comment]
Still having a problem getting the menus to load. I replaced the minified version of Angular.js with the non minified version (1.3.14) which produced this more readable error.

Error: [$injector:modulerr] Failed to instantiate module slatwalladmin due to:
[$injector:modulerr] Failed to instantiate module ngSlatwall due to:
[$injector:nomod] Module 'ngSlatwall' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=ngSlatwall

**Comment by deanlaw** [comment]
Any update on this issue? I have a brand new standalone install on OS X running CF 11 and MySql and from the get go I am running into this angular error. I can create a new admin account at the end of the install, but then I can't navigate anywhere because of the js error. Clicking on any of the navigation items does nothing. I'm trying to evaluate the product, so any help would be greatly appreciated.

**Comment by rmarchandTen24** [comment]
this should be resolved in the latest master. The issue was the result of a
badly minified file.

**Comment by deanlaw** [comment]
I'm still having the issue with the most recent master. Here is my setup:

- OS X - ver. 10.10.3
- Apache ver. 2.4.10
- MySQL ver. 5.5.28
- Chrome ver. 42.0.2311.90 (64-bit)

I have shut down CF, deleted files, replaced files, deleted DB tables, cleared browser cache, re-installed and still have the problem. I was digging a little deeper and realized that besides the angular.js error I am also getting a 500 error when this url is being called "/?slatAction=api:js.ngslatwall&instantiationKey=11763809-E47D-CCFD-70730AED7FC2DACD". Does that help to point me in a direction to look?

**Comment by ian-a-hickey** [comment]
I was able to pull the latest master without issue on a similar setup. The
error message you are receiving means that Slatwall thinks there is an
error in a javascript file (admin/client/js folder). I've had success just
adding ?reload=true to the end of the URL if you haven't already. What does
your url string look like? Are you hitting localhost/Slatwall/? Also, you
could try disabling the cache temporarily in case any of that old angular
files are being pulled from cache rather than new (I know you cleared the
cache files, but I've seen a similar issue). To turn your cache off,
rightclick on a webpage -> inspect element -> Network tab -> disable cache
checkbox. Then do a slatwall/?reload=true and see if you get a different
result. Or just try hitting Slatwall in a different browser to check if it
was Chrome saving the old Javascript.

**Comment by rmarchandTen24** [comment]
Hi Dean, can download 4.0.011

**Comment by deanlaw** [comment]
I just downloaded and installed 4.0.011 and received the same result. I have tried adding ?reload=true to the end of the URL with no change to the behavior. This is my local dev machine, so I don't have any of the caching options turned on in the CF admin and I have emptied my browser cache numerous times. I have also tried accessing the install from multiple browsers with the same result. Two things to note though, which I don't know if they have any bearing on the issue; every time that I have done the install, it has timed out prior to getting to the point of adding the new admin account and I also have the slatwall files in the root of my test site, not in a subdirectory. 

With the install timeout, I simply reload the URL and am presented with the create admin user screen. I see the angular error in my console, but it allows me to create the admin user. However, once at the dashboard, I cannot access any of the menu items. Is it possible that the install is not completing properly? Are there any settings in my CF admin that I should be changing to prevent the timeout?

As for my setup, I have a virtual website setup in Apache and I copied the Slatwall files from the download into the root folder. Do they need to stay in a subdirectory? Does this make any difference?

**Comment by deanlaw** [comment]
Ok, install timeout is not the issue, as I just bumped up the request timeout in CF admin, re-installed (which completed successfully) and I still get the angular.js error.

**Comment by rmarchandTen24** [comment]
Ah, the timeout is an important clue. If you are getting a java heap error
from the ngslatwall script it may be that you need to bump up your ram in
the coldfusion admin.

**Comment by bowler865** [comment]
Just uploaded a completely fresh set of files, 4.0.011, and still getting the same angular.js error ($injector:modulerr). I've cleared cached files in browser as well as CF server.

Operating System:	Windows Server 2012
		CFML Server:		ColdFusion Server: 11,0,04,293328
		DB Dialect: 		MySQL
		Slatwall Version:	4.0.011

**Comment by deanlaw** [comment]
I saw that you had posted 4.0.012, so I downloaded it and ran through the install. I still get the error. However, when looking at the network requests, I am seeing that this script ?slatAction=api:js.ngslatwall&instantiationKey=D4AF372D-F37A-49C4-F14E61FFDD60EAB1 is throwing a 500 error. Does that help at all?

**Comment by rmarchandTen24** [comment]
If the 500 error is a java heap error you will need to increase the amount of ram available to coldfusion via the administrator. A decent amount of memory is needed for the initial generation of the JavaScript.
Ryan

**Comment by deanlaw** [comment]
I accessed the link that is throwing the 500 error directly and was able to get a CF error dump. The error type is a java.lang.NullPointerException type, which is being thrown from cfJavaProxy2ecfc1365799477$func_RESOLVEMETHODBYPARAMS.runFunction(/Users/dean/Sites/clients/slatwall/org/Hibachi/YUIcompressor/javaloader/JavaProxy.cfc:195). I doubled the Java heap size to 1024/2048 (min/max) in the CF admin, restarted CF and still get the 500 error. I have hit the site a number of times with the reload variable to no avail.

**Comment by deanlaw** [comment]
Could this be a JVM version issue? I'm currently running ver. 1.7.0_51 on OS X 10.10.3

**Comment by ian-a-hickey** [comment]
CF11 works with JDK 7 (1.7) for update 2 and earlier, JDK 8 update 3 and
later. Java 8 has some really big changes in it. I use 1.7 with CF10.
You're erroring out on yuicompressor which uses javaloader, so It could be
an issue between cf11, JDK, and javaloader? I read some people claiming a
500 error on cf11 due to an issue with Apache connector also. You could try
cf10 which is what many of us use.

**Comment by rmarchandTen24** [comment]
If you are having issues with the compression you can eliminate that step
via configuration for now.

add <cfset variables.framework.debugflag=true />
to custom/config/configFramework.cfm

we will be compressing ngslatwall proactively in a future release to avoid
this

**Comment by deanlaw** [comment]
Ryan, I tried that and it did not work. However, with all this talk about the JVM and javaloader, I was poking around in the CF admin and saw that I had checked off the "Disable access to internal ColdFusion Java components" option. I unchecked it and was able to load Slatwall without error. I re-checked it and reloaded Slatwall, the error returned. Turned it back off, and the admin loaded fine. So it looks like javaloader may need access to an internal component in able to work properly.

**Comment by rmarchandTen24** [comment]
Ok, glad you got it :D, thanks for the assist Ian.
We will be removing this dependency in the future by pre-minifying. One of
the other bonuses will be that we will be using Uglify instead of YUI
compressor as in gets way better compression results.

**Comment by rmarchandTen24** [comment]
just an update on this item. In the latest bleeding edge, 4.1.002.001 we have converted all generated javascript (ngslatwall) to static files. This should eliminate the need for this setting down the road. We are now using a gulp workflow with uglify and typescript. The file sizes have also been reduced to 12% of what they are originally. Currently all JS (for slatwall admin's angular implementation) when gzipped is about 192kb collectively. We currently plan to release this in 4.2.

**Comment by rmarchandTen24** [comment]
just a bump on this. All js is now static and build based in 4.2. Expect a patch that modularizes and bundles the js using webpack soon. This means instead of using a bunch of coldfusion generated script tags. There will be one bundle.js. This also means that we will be able to deploy to Commonjs,AM, and ES6 javascript implementations thanks to typescript.
